apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-demo-app
  template:
    metadata:
      labels:
        app: python-demo-app
    spec:
      containers:
      - name: python-demo-app
        image: byogi06/python-demo-app:latest
        ports:
        - containerPort: 80